# Generated by Django 4.0.5 on 2022-06-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='littype',
            field=models.CharField(blank=True, default='Type of Litterature', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='app/files/covers'),
        ),
    ]
