# Generated by Django 4.0.5 on 2022-06-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_postform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(default=None, upload_to='app/files/covers'),
        ),
        migrations.AlterField(
            model_name='info',
            name='littype',
            field=models.CharField(default='Type of Litterature', max_length=100),
        ),
    ]
