# Generated by Django 4.0.5 on 2022-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_info_image_alter_info_littype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='details',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='app/files/covers'),
        ),
        migrations.AlterField(
            model_name='info',
            name='littype',
            field=models.CharField(blank=True, default='Type of Litterature', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
